name: Plan & Deploy Infrastructure

permissions:
  contents: write
  pull-requests: write 
  issues: write
  id-token: write
  packages: none

on:
  pull_request:
    branches:
      - demo
  push:
    branches:
      - feature/**

jobs:
  tflint:
    uses: ./.github/workflows/tflint-check.yml
  tfsec:
    uses: ./.github/workflows/tfsec-check.yml
  checkov:
    uses: ./.github/workflows/checkov-check.yml

  plan-infra:
    uses: ./.github/workflows/terraform-plan.yml
    needs: 
      - tflint
      - tfsec
      - checkov
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }} 

  deploy-infra:
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/terraform-apply.yml
    needs: 
      - tflint
      - tfsec
      - checkov
      - plan-infra
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }} 